### ISSUE TITLE
Fix configs and deps

### ISSUE THREAD

**Issue by tysky** [Cado-Labs/auth-http-provider#1]
I think we don't need the packages `eslint-plugin-jsx-a11y`, `eslint-plugin-node` here.
Also in `eslint` config it's better to change `ecmaVersion` option to `"ecmaVersion": "latest"`

**Comment by nulldef** [comment]
Unfortunately, I can't delete `eslint-plugin-node`, 'cause it required by `eslint-config-umbrellio`

**Comment by tysky** [comment]
ok, let's keep this plugin 👍
